restaurants/myrestaurants/urls.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
#@ Author    :   Eva.Chen
#@ Contact   :   1985467552@qq.com
#@ Time      :   2020/3/31 5:03 下午
#@ Desc      :   None
'''
from django.urls import path, re_path
from . import views

# namespace
app_name = 'myrestaurants'
urlpatterns = [

    # 查看餐厅列表
    path('', views.RestaurantList.as_view(), name='restaurant_list'),

    # 查看餐厅详情, 如/myrestaurants/restaurant/1/
    re_path(r'^restaurant/(?P<pk>\d+)/$',
        views.RestaurantDetail.as_view(), name='restaurant_detail'),

    # 创建餐厅, 如：/myrestaurants/restaurant/create/
    re_path(r'^restaurant/create/$', views.RestaurantCreate.as_view(), name='restaurant_create'),

    # 编辑餐厅详情, 如: /myrestaurants/restaurant/1/edit/
    re_path(r'^restaurant/(?P<pk>\d+)/edit/$',
        views.RestaurantEdit.as_view(), name='restaurant_edit'),

    # 创建菜品 ex.: /myrestaurants/restaurant/1/dishes/create/
    re_path(r'^restaurant/(?P<pk>\d+)/dishes/create/$',
            views.DishCreate.as_view(), name='dish_create'),

    # 编辑菜品, ex.: /myrestaurants/restaurant/1/dishes/1/edit/
    re_path(r'^restaurant/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/edit/$',
            views.DishEdit.as_view(), name='dish_edit'),

    # 查看菜品信息 ex: /myrestaurants/restaurants/1/dishes/1/
    re_path(r'^restaurant/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/$',
            views.DishDetail.as_view(), name='dish_detail'),

    # 创建餐厅评论, /myrestaurants/restaurant/1/reviews/create/
    re_path(r'^restaurant/(?P<pk>\d+)/reviews/create/$',
            views.review_create, name='review_create'),

]

restaurants/restaurants/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from myrestaurants import views



urlpatterns = [
    url('^admin/', admin.site.urls),
    url(r'^myrestaurants/', include('myrestaurants.urls')),
    url(r'^accounts/', include('users.urls')),
    url(r'^index/', views.RestaurantList.as_view(), name='restaurant_list'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/users/urls.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
#@ Author    :   Eva.Chen
#@ Contact   :   1985467552@qq.com
#@ Time      :   2020/4/11 4:26 下午
#@ Desc      :   None
'''

from django.urls import re_path
from . import views

app_name = 'users'
urlpatterns = [
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^user/(?P<pk>\d+)/profile/$', views.profile, name='profile'),
    re_path(r'^user/(?P<pk>\d+)/profile/update/$', views.profile_update, name='profile_update'),
    re_path(r'^user/(?P<pk>\d+)/pwdchange/$', views.pwd_change, name='pwd_change'),
    re_path(r'^logout/$', views.logout, name='logout'),
]

restaurants/myrestaurants/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.urls import reverse


class Restaurant(models.Model):
    name = models.TextField()
    address = models.TextField(blank=True, default='')
    telephone = models.TextField(blank=True, default='')
    url = models.URLField(blank=True, null=True)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myrestaurants:restaurant_detail', args=[str(self.id)])


class Dish(models.Model):
    name = models.TextField()
    description = models.TextField(blank=True, default='')
    price = models.DecimalField('USD amount', max_digits=8, decimal_places=2, blank=True, null=True)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)
    image = models.ImageField(upload_to="myrestaurants", blank=True, null=True)
    restaurant = models.ForeignKey(Restaurant, null=True, related_name='dishes', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myrestaurants:dish_detail', args=[str(self.restaurant.id), str(self.id)])


# This Abstract Review can be used to create RestaurantReview and DishReview
class Review(models.Model):
    RATING_CHOICES = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))
    rating = models.PositiveSmallIntegerField('Rating (stars)', blank=False, default=3, choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)

    class Meta:
        abstract = True

    '''
    class Meta:
        # 按Priority降序, order_date升序排列.
        get_latest_by = ['-priority', 'order_date']
        # 自定义数据库里表格的名字
        db_table = 'music_album'
        # 按什么排序
        ordering = ['pub_date']
        # 定义APP的标签
        app_label = 'myapp'
        # 声明此类是否为抽象，Django就会认为这个模型是抽象类，不会在数据库里创建review的数据表
        abstract = True
        # 添加授权
        permissions = (("can_deliver_pizzas", "Can deliver pizzas"),)
    '''

class RestaurantReview(Review):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name="reviews")

    def __str__(self):
        return "{} review".format(self.restaurant.name)

restaurants/myrestaurants/forms.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
#@ Author    :   Eva.Chen
#@ Contact   :   1985467552@qq.com
#@ Time      :   2020/3/31 5:39 下午
#@ Desc      :   None
'''

from django.forms import ModelForm, TextInput, URLInput, ClearableFileInput
from .models import Restaurant, Dish

class RestaurantForm(ModelForm):
    class Meta:
        model = Restaurant
        # 表示将model中，除了exclude属性中列出的字段之外的所有字段，添加到表单类中作为表单字段。
        exclude = ('user', 'date',)

        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'address': TextInput(attrs={'class': 'form-control'}),
            'telephone': TextInput(attrs={'class': 'form-control'}),
            'url': URLInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'name': '名称',
            'address': '地址',
            'telephone': '电话',
            'url': '网站',
        }

class DishForm(ModelForm):
    class Meta:
        model = Dish
        exclude = ('user', 'date', 'restaurant',)

        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'description': TextInput(attrs={'class': 'form-control'}),
            'price': TextInput(attrs={'class': 'form-control'}),
            'image': ClearableFileInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'name': '菜名',
            'description': '描述',
            'price': '价格(元)',
            'image': '图片',
        }

restaurants/myrestaurants/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404,render
from django.urls import reverse
from django.views.generic import DetailView, ListView, UpdateView
from django.views.generic.edit import CreateView
from .models import RestaurantReview, Restaurant, Dish
from .forms import RestaurantForm, DishForm

class RestaurantList(ListView):
    queryset = Restaurant.objects.all().order_by('-date')
    context_object_name = 'latest_restaurant_list'
    template_name = 'myrestaurants/restaurant_list.html'

class RestaurantDetail(DetailView):
    model = Restaurant
    template_name = 'myrestaurants/restaurant_detail.html'

    def get_context_data(self, **kwargs):
        context = super(RestaurantDetail, self).get_context_data(**kwargs)
        context['RATING_CHOICES'] = RestaurantReview.RATING_CHOICES
        return context

class RestaurantCreate(CreateView):
    model = Restaurant
    template_name = 'myrestaurants/form.html'
    form_class = RestaurantForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(RestaurantCreate, self).form_valid(form)

class RestaurantEdit(UpdateView):
    model = Restaurant
    template_name = 'myrestaurants/form.html'
    form_class = RestaurantForm

class DishDetail(DetailView):
    model = Dish
    template_name = 'myrestaurants/dish_detail.html'

class DishCreate(CreateView):
    model = Dish
    template_name = 'myrestaurants/form.html'
    form_class = DishForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.restaurant = Restaurant.objects.get(id=self.kwargs['pk'])
        return super(DishCreate, self).form_valid(form)

class DishEdit(UpdateView):
    model = Dish
    template_name = 'myrestaurants/form.html'
    form_class = DishForm

def review_create(request, pk):
    restaurant = get_object_or_404(Restaurant, pk=pk)
    review = RestaurantReview(
        rating=request.POST['rating'],
        comment=request.POST['comment'],
        user=request.user,
        restaurant=restaurant)
    review.save()
    return HttpResponseRedirect(reverse('myrestaurants:restaurant_detail', args=[pk]))

restaurants/templates/myrestaurants/dish_detail.html
{% extends "users/base.html" %}
{% block content %}
<div class="info-title">
  <div style="display:inline-block;">{{ dish.name }}</div>
  {% if request.user == dish.user %}
  <a href="{% url 'myrestaurants:dish_edit' dish.restaurant.id dish.id%}"><i class="icon-edit"></i></a>
  {% endif %}
</div>
<div class="info-list">
  <div class="info-item">餐厅:
    <a href="{% url 'myrestaurants:restaurant_detail' dish.restaurant.id %}">{{ dish.restaurant.name}}</a>
  </div>
  <div class="info-item">
  {{ dish.description }}
  </div>
  <div class="info-item">
  {% if dish.image %}
  <p><img src="{{ dish.image.url }}"/></p>
  {% endif %}
  </div>
  <div class="info-item">
    价格: {{ dish.price }}元
  </div>
</div>

{% endblock %}

restaurants/templates/myrestaurants/form.html
{% extends "users/base.html" %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
    </div>
{% endif %}

{% for field in form.visible_fields %}
    <div class="form-group">
    {{ field.label_tag }}
    {{ field }}
    {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
    </div>
{% endfor %}
    <div class="form-group btn-submit">
         <input class="btn btn-primary" type="submit" value="提交"/>
    </div>
</form>

{% endblock %}

restaurants/templates/myrestaurants/restaurant_detail.html
{% extends "users/base.html" %}

{% block content %}
<div class="restaurant-detail">
    <div class="info-title">
        <div style="display:inline-block;">{{ restaurant.name }}</div>
        {% if request.user == restaurant.user %}
            <a href="{% url 'myrestaurants:restaurant_edit' restaurant.id %}"><i class="icon-edit"></i></a>
        {% endif %}
    </div>
    <div class="info-list">
        <div class="info-item">
            <i class="icon-address"></i>
            {% if restaurant.address %}
            {{ restaurant.address }}
            {% else %}暂时没有地址
            {% endif %}
        </div>
        <div class="info-item">
            <i class="icon-telephone"></i>
            {% if restaurant.telephone %}
            {{ restaurant.telephone }}
            {% else %}暂时没有电话
            {% endif %}
        </div>
        <div class="info-item">
            <i class="icon-website"></i>
           {% if restaurant.url %}
            {{ restaurant.url }}
            {% else %}暂时没有网址
            {% endif %}
        </div>
    </div>

    <div class="info-title">菜单
      {% if request.user.is_authenticated and request.user == restaurant.user %}
        <a href="{% url 'myrestaurants:dish_create' restaurant.id %}"><i class="icon-add"></i></a>
      {% endif %}
    </div>

    <ul>
        {% for dish in restaurant.dishes.all %}
        <li class="info-item">
            <a href="{% url 'myrestaurants:dish_detail' restaurant.id dish.id %}">{{ dish.name }}</a> - {{ dish.price }}元
        </li>
        {% empty %}<li class="info-item">对不起，该餐厅还没有菜肴。</li>
        {% endfor %}
    </ul>

    <div class="info-title">用户点评</div>
    {% if restaurant.reviews.all %}
    <ul>
        {% for review in restaurant.reviews.all %}
        <li class="info-item">
            <p>{{ review.rating}}星, {{ review.user }}点评, {{ review.date | date:"Y-m-d" }}</p>
            <p>{{ review.comment }}</p>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p class="info-item">目前还没有用户点评。</p>
    {% endif %}

    <div class="info-title">添加点评</div>
    {% if request.user.is_authenticated %}
    <form action="{% url 'myrestaurants:review_create' restaurant.id %}" method="post">
        {% csrf_token %}
        <textarea name="comment" id="comment"></textarea>
        <p class="info-item">
        {% for rate in RATING_CHOICES %}
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="rating" id="rating{{ forloop.counter }}" value="{{ rate.0 }}" >
                <label class="form-check-label" for="choice{{ forloop.counter }}">{{ rate.0 }}星</label>
            </div>
        {% endfor %}
         </p>
         <div class="form-group btn-submit" style="text-align:left;">
             <input class="btn btn-primary" type="submit" value="提交"/>
        </div>
    </form>
    {% else %}
    <p class="info-item">请先<a href="{% url 'users:login' %}?next={% firstof request.path '/' %}">登录</a>再评论。</p>
    {% endif %}
</div>
{% endblock %}

restaurants/templates/myrestaurants/restaurant_list.html
{% extends "users/base.html" %}
{% block content %}
<div class="info-title">餐厅列表</div>
<ul class="list-group">
    {% for restaurant in latest_restaurant_list %}
    <li class="list-group-item"><a href="{% url 'myrestaurants:restaurant_detail' restaurant.id %}">
        {{ restaurant.name}}
    </a></li>
    {% empty %}<li>对不起，目前还没有餐厅</li>
    {% endfor %}
</ul>

{% if request.user.is_authenticated %}
<div class="form-group btn-submit" style="margin-top:30px;">
    <a role="button" class="btn btn-outline-primary" href="{% url 'myrestaurants:restaurant_create'%}">添加餐厅</a>
</div>
{% else %}
<p class="info-item">请<a href="{% url 'users:login' %}?next={% url 'myrestaurants:restaurant_create' %}">登录</a>后添加餐厅</p>
{% endif %}
{% endblock%}