restaurants/myrestaurants/urls.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
#@ Author    :   Eva.Chen
#@ Contact   :   1985467552@qq.com
#@ Time      :   2020/3/31 5:03 下午
#@ Desc      :   None
'''
from django.urls import path, re_path
from . import views

# namespace
app_name = 'myrestaurants'
urlpatterns = [

    # 查看餐厅列表
    path('', views.RestaurantList.as_view(), name='restaurant_list'),

    # 查看餐厅详情, 如/myrestaurants/restaurant/1/
    re_path(r'^restaurant/(?P<pk>\d+)/$',
        views.RestaurantDetail.as_view(), name='restaurant_detail'),

    # 创建餐厅, 如：/myrestaurants/restaurant/create/
    re_path(r'^restaurant/create/$', views.RestaurantCreate.as_view(), name='restaurant_create'),

    # 编辑餐厅详情, 如: /myrestaurants/restaurant/1/edit/
    re_path(r'^restaurant/(?P<pk>\d+)/edit/$',
        views.RestaurantEdit.as_view(), name='restaurant_edit'),

    # 创建菜品 ex.: /myrestaurants/restaurant/1/dishes/create/
    re_path(r'^restaurant/(?P<pk>\d+)/dishes/create/$',
            views.DishCreate.as_view(), name='dish_create'),

    # 编辑菜品, ex.: /myrestaurants/restaurant/1/dishes/1/edit/
    re_path(r'^restaurant/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/edit/$',
            views.DishEdit.as_view(), name='dish_edit'),

    # 查看菜品信息 ex: /myrestaurants/restaurants/1/dishes/1/
    re_path(r'^restaurant/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/$',
            views.DishDetail.as_view(), name='dish_detail'),

    # 创建餐厅评论, /myrestaurants/restaurant/1/reviews/create/
    re_path(r'^restaurant/(?P<pk>\d+)/reviews/create/$',
            views.review_create, name='review_create'),

]

restaurants/restaurants/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from myrestaurants import views



urlpatterns = [
    url('^admin/', admin.site.urls),
    url(r'^myrestaurants/', include('myrestaurants.urls')),
    url(r'^accounts/', include('users.urls')),
    url(r'^index/', views.RestaurantList.as_view(), name='restaurant_list'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/users/urls.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
#@ Author    :   Eva.Chen
#@ Contact   :   1985467552@qq.com
#@ Time      :   2020/4/11 4:26 下午
#@ Desc      :   None
'''

from django.urls import re_path
from . import views

app_name = 'users'
urlpatterns = [
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^user/(?P<pk>\d+)/profile/$', views.profile, name='profile'),
    re_path(r'^user/(?P<pk>\d+)/profile/update/$', views.profile_update, name='profile_update'),
    re_path(r'^user/(?P<pk>\d+)/pwdchange/$', views.pwd_change, name='pwd_change'),
    re_path(r'^logout/$', views.logout, name='logout'),
]

restaurants/users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
'''
Django Auth模块自带User模型所包含字段
username：用户名
email: 电子邮件
password：密码
first_name：名
last_name：姓
is_active: 是否为活跃用户。默认是True
is_staff: 是否为员工。默认是False
is_superuser: 是否为管理员。默认是False
date_joined: 加入日期。系统自动生成。
'''

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_query_name='profile')
    org = models.CharField(
        'Organization', max_length=128, blank=True)
    telephone = models.CharField(
        'Telephone', max_length=50, blank=True)
    mod_date = models.DateTimeField(
        'Last modified', auto_now=True)

    class Meta:
        verbose_name = 'User Profile'

    def __str__(self):
        return self.user

restaurants/users/forms.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
#@ Author    :   Eva.Chen
#@ Contact   :   1985467552@qq.com
#@ Time      :   2020/4/11 4:36 下午
#@ Desc      :   None
'''
from django import forms
from django.contrib.auth.models import User
from django.forms import TextInput
import re

def email_check(email):
    pattern = re.compile(r"\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?")
    return re.match(pattern, email)
# 自定义验证规则
def telephone_check(telephone):
    pattern = re.compile(r'^(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57])[0-9]{8}$')
    if not re.match(pattern, telephone):
        raise forms.ValidationError("手机号格式不正确")

class RegistrationForm(forms.Form):

    username = forms.CharField(label='Username', max_length=50)
    email = forms.EmailField(label='Email',)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if len(username) < 6:
            raise forms.ValidationError("Your username must be at least 6 characters long.")
        elif len(username) > 50:
            raise forms.ValidationError("Your username is too long.")
        else:
            filter_result = User.objects.filter(username__exact=username)
            if len(filter_result) > 0:
                raise forms.ValidationError("Your username already exists.")

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if email_check(email):
            filter_result = User.objects.filter(email__exact=email)
            if len(filter_result) > 0:
                raise forms.ValidationError("Your email already exists.")
        else:
            raise forms.ValidationError("Please enter a valid email.")

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if len(password1) < 6:
            raise forms.ValidationError("Your password is too short.")
        elif len(password1) > 20:
            raise forms.ValidationError("Your password is too long.")

        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Password mismatch. Please enter again.")

        return password2

class LoginForm(forms.Form):

    username = forms.CharField(label='Username', max_length=50)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        filter_result = User.objects.filter(username__exact=username)
        if not filter_result:
            raise forms.ValidationError("This username does not exist. Please register first")

        return username

class ProfileForm(forms.Form):
    first_name = forms.CharField(label='名', widget=TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='姓', widget=TextInput(attrs={'class': 'form-control'}))
    telephone = forms.CharField(validators=[telephone_check], label='电话', widget=TextInput(attrs={'class': 'form-control'}))
    org = forms.CharField(label='公司', widget=TextInput(attrs={'class': 'form-control'}))

class PwdChangeForm(forms.Form):
    old_password = forms.CharField(label='旧密码', widget=TextInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(label='新密码', widget=forms.PasswordInput)
    new_password2 = forms.CharField(label='确认密码', widget=forms.PasswordInput)
    def clean_new_password1(self):
        password1 = self.cleaned_data.get('new_password1')

        if len(password1) < 6:
            raise forms.ValidationError("Your password is too short.")
        elif len(password1) > 20:
            raise forms.ValidationError("Your password is too long.")

        return password1

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Password mismatch. Please enter again.")

        return password2

restaurants/users/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from .models import UserProfile
from django.contrib import auth
from .forms import RegistrationForm, LoginForm, ProfileForm, PwdChangeForm
from django.http import HttpResponseRedirect
from django.urls import reverse

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password2']

            user = User.objects.create_user(username=username, password=password, email=email)
            user_profile = UserProfile(user=user)
            user_profile.save()

            return HttpResponseRedirect("/accounts/login/")
    else:
        form = RegistrationForm()

    return render(request, 'users/register.html', {'form': form})

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = auth.authenticate(username=username, password=password)

            if user is not None and user.is_active:
                if user.is_superuser:
                    return redirect('/admin/')
                else:
                    auth.login(request, user)
                    return HttpResponseRedirect(reverse('myrestaurants:restaurant_list', ))

            else:
                return render(request, 'users/login.html', {'form': form, 'message': 'Wrong password.Please try again'})

    else:
        form = LoginForm()

    return render(request, 'users/login.html', {'form': form})

def profile(request, pk):
    profile = get_object_or_404(UserProfile, user_id=pk)
    return render(request, 'users/profile.html', {'profile': profile})

def pwd_change(request, pk=None):
    if request.method == "POST":
        form = PwdChangeForm(request.POST)
        if form.is_valid():
            old_password = request.POST.get("old_password")
            new_password1 = request.POST.get("new_password1")
            new_password2 = request.POST.get("new_password2")
            # 得到当前登录的用户，判断旧密码是不是和当前的密码一样
            username = request.user  # 打印的是当前登录的用户名
            user = User.objects.get(id=pk)  # 查看用户
            ret = user.check_password(old_password)  # 检查密码是否正确
            if ret:
                user.set_password(new_password1)  # 如果正确就给设置一个新密码
                user.save()  # 保存
                return HttpResponseRedirect(reverse('users:login'))
            else:
                return render(request, "pwd_change.html", {"message": "输入密码有误"})
    else:
        form = PwdChangeForm()
    return render(request, 'users/pwd_change.html', {'form': form})

def profile_update(request,pk=None):
    profile = UserProfile.objects.get(user_id=pk)
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            user = User.objects.get(pk=pk)
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()
            profile.telephone = form.cleaned_data['telephone']
            profile.org = form.cleaned_data['org']
            profile.save()
            return HttpResponseRedirect(reverse('users:profile', args=[pk]))
    else:
        form = ProfileForm(data={'first_name': profile.user.first_name,
                                 'last_name': profile.user.last_name,
                                 'org': profile.org,
                                 'telephone': profile.telephone})

    return render(request, 'users/profile_update.html', {'form': form})

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('users:login'))

restaurants/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block title %} User Information{% endblock %} </title>
<meta charset="utf-8">
<meta name="keywords" content="{% block keywords %} some keywords{% endblock %} ">
<meta name="description" content="{% block description %} Django web application example.{% endblock %}">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'myrestaurants/css/common.css' %}">
<link rel="stylesheet" href="{% static 'myrestaurants/css/base.css' %}">
    {% block header %}
    {% endblock %}
</head>
<body style="overflow:scroll;">
<nav class="navbar navbar-expand-lg navbar-light bg-orange nav-base">
    <a class="navbar-brand" href="{% url 'myrestaurants:restaurant_list' %}">
        <i class="icon icon-home"></i>

    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar" aria-controls="myNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="myNavbar">
        <div class="navbar-nav" style="margin-left:auto!important;">
        {% if user.is_authenticated %}
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="icon icon-user"></i>{{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'users:profile' user.id %}">我的账户</a>
                    <a class="dropdown-item"  href="{% url 'users:logout' %}">退出登录</a>
                </div>
            </div>
            {% else %}
            <div class="nav-item" >
                <a class="btn btn-primary"  href="{% url 'users:login' %}">登录</a>
                <a class="btn btn-outline-primary"  href="{% url 'users:register' %}">注册</a>
            </div>
        {% endif %}
        </div>
    </div>
</nav>
<main >
    <div class="container">
         <div class="base">
          {% block content %}
          {% if error_message %}<p><strong>{{ error_message}}</strong></p>{% endif %}
          {% endblock %}
         </div>
    </div>
</main>
<footer class="footer">
    {% block footer %}{% endblock %}
</footer>
<!--End of Footer-->

<!-- Bootstrap core JavaScript
================================================== -->

<script src="{% static 'myrestaurants/js/jquery-3.4.1.slim.min.js'%}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

restaurants/templates/users/login.html
{% extends "users/base.html" %}
{% block content %}
{% if message %}
<div class="alert alert-danger" role="alert">{{ message }}</div>
{% endif %}
<div class="login">
    <div class="form-wrapper">
        <div class="title">Login</div>
        <form method="post" action="" enctype="multipart/form-data">
           {% csrf_token %}
           {% for field in form %}
                <div class="form-group">
                    {% if field.errors %}
                    <div class="alert alert-danger" role="alert">{{ field.errors }}</div>
                    {% endif %}
                    {{ field.label_tag }} {{ field }}
                    {% if field.help_text %}
                     <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
           {% endfor %}
           <div class="btn-list">
               <div class="btn-item">
                   <input class="btn btn-primary" type="submit" value="Login">
               </div>
               <div class="btn-item">
                   <a class="btn btn-outline-primary" href="/accounts/register">Register</a>
               </div>
           </div>
        </form>
    </div>
</div>
{% endblock %}

restaurants/templates/users/profile.html
{% extends "users/base.html" %}

{% block content %}
<div class="profile">
    <div class="info-section">
        <div class="info-title">Account Info</div>
        <ul >
            <li><span>Username:</span>{{ profile.user.username }}</li>
            <li><span>Email: </span>{{ profile.user.email }}</li>
        </ul>
    </div>
    <div class="info-section">
        <div class="info-title">My Profile</div>
        <ul>
            <li><span>First Name:</span>{{ profile.user.first_name }}</li>
            <li><span>Last Name: </span>{{ profile.user.last_name }}</li>
            <li><span>Telephone: </span>{{ profile.telephone }}</li>
            <li><span>Organization:</span>{{ profile.org }}</li>
        </ul>
    </div>
    <div class="btn-list">
        <a class="btn btn-outline-primary" href="{% url 'users:profile_update' profile.user.id  %}">Edit Profile</a>
        <a class="btn btn-outline-primary" href="{% url 'users:pwd_change' profile.user.id  %}">Change Password</a>
    </div>
</div>

{% endblock %}

restaurants/templates/users/profile_update.html
{% extends "users/base.html" %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {% if field.errors %}
        <div class="alert alert-danger" role="alert">{{ field.errors }}</div>
        {% endif %}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
    {% endfor %}
    <div class="form-group btn-submit">
         <input class="btn btn-primary" type="submit" value="提交"/>
    </div>
</form>

{% endblock %}

restaurants/templates/users/pwd_change.html
{% extends "users/base.html" %}
{% block content %}
{% if message %}
    {{ message }}
{% endif %}
<form action="" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {% if field.errors %}
        <div class="alert alert-danger" role="alert">{{ field.errors }}</div>
        {% endif %}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
    {% endfor %}
    <div class="form-group btn-submit">
         <input class="btn btn-primary" type="submit" value="提交"/>
    </div>
</form>
{% endblock %}

restaurants/templates/users/register.html
{% extends "users/base.html" %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {% if field.errors %}
        <div class="alert alert-danger" role="alert">{{ field.errors }}</div>
        {% endif %}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
    {% endfor %}
    <div class="form-group btn-submit">
         <input class="btn btn-primary" type="submit" value="提交"/>
    </div>
</form>

{% endblock %}